### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by pengzhile** [Nasller/plugin-myagent#1]
最好不要直接改动jetbrains自己的类文件，不同于改动jre的类，jetbrains自己类有其所有权，风险比较大。
我看你hook了一些remotesdk的类，是想处理远程开发的激活吗？远程开发的IDE也有自己的vmoptions，配置一下就可以了。

**Comment by Nasller** [comment]
这个是用来一键看日志的，一开始没改，后来我们运维加了堡垒机remoteRun就用不了了，他不支持堡垒机的跳转，我就自己diy了，之前用的方法是替换文件，但是太麻烦了而且他jar替换文件有限制，用你的框架正好。暂时用着没问题:)
