### ISSUE TITLE
我把jar放到这个目录下，好像不生效，能否指导一下

### ISSUE THREAD

**Issue by sdhzwc** [Nasller/plugin-myagent#4]
![image](https://github.com/Nasller/plugin-myagent/assets/46134044/260a23a5-71bd-4a1c-8bf5-b2623622fed5)

**Comment by Nasller** [comment]
你想生效什么？

**Comment by sdhzwc** [comment]
> 你想生效什么？

就是插件收费拦截，比如彩虹括号

**Comment by Nasller** [comment]
他改方式了，这个已经不适用了
