### ISSUE TITLE
反斜杠的问题解决了，文件也上传了。但是还是运行不了，请教一下。

### ISSUE THREAD

**Issue by longstorying** [Nasller/plugin-myagent#5]
![image](https://github.com/Nasller/plugin-myagent/assets/37175458/b49fb7f9-00f9-49e4-bf34-17f9f3cc21f6)
![image](https://github.com/Nasller/plugin-myagent/assets/37175458/18982c8c-497c-4b03-94b1-0fc0b678d127)

**Comment by Nasller** [comment]
是不是配置错了
![image](https://github.com/Nasller/plugin-myagent/assets/26132153/ee9df485-132c-4b38-a650-76189979b15b)
百度看看
